version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-tools
    tty: true
    image: "{{image}}"
    container_name: "{{containerName}}"
    ports: {{#each ports}}
      - "{{this}}:{{this}}"{{/each}}
    volumes:
      - .:/app
      - node_modules:/app/node_modules {{#ifCond images.length '>' 0}}
    links: {{#each images}}
      -  {{this}}{{/each}}{{/ifCond}}
    environment:
      NODE_ENV: "development"{{#each envs as |value key|}}
      {{key}}: {{value}}{{/each}}{{#each images}}
  {{this}}:
    image: {{this}}
{{/each}}

volumes:
  node_modules:
